DELIMITER //

CREATE PROCEDURE TO_PUBLISH_OPENRICE_TABLES()
BEGIN

/*
2. DATA PROCESSING

PERFORM ETL FOR DATA CLEANSING BY STORED PROCEDURE IN MYSQL DATABASE

RAW TABLE FROM PART 1 WEB SCRAPPING
OPENRICE.RAW_RESTAURANTS: RESTAURANTS INFORMATION 
OPENRICE.RAW_CATEGORIES: CATEGORES MASTER TABLE
OPENRICE.RAW_DISTRICTS: DISTRICT MASTER TABLE

*/

-- CREATE TABLE WITH RESTAURANT ID & CLEAN UP DATA TYPE
-- ALSO REMOVE DUPLICATED RESTAURANT (SAME NAME + SAME ADDRESS)
DROP TABLE IF EXISTS  NEW_TBL;

CREATE TEMPORARY TABLE NEW_TBL 
SELECT * , ROW_NUMBER() OVER (PARTITION BY ZH_NAME,ENG_NAME,ENG_ADDRESS ORDER BY BOOKMARK DESC, REVIEW_CNT DESC, PHOTO_CNT DESC) AS ROW_NUNBER
FROM OPENRICE.RAW_RESTAURANTS;


DROP TABLE IF EXISTS PUBLISH_RESTAURANTS;

CREATE TABLE PUBLISH_RESTAURANTS 
SELECT 
	DISTINCT
	ROW_NUMBER() OVER (ORDER BY ZH_NAME,ENG_NAME,ENG_ADDRESS) AS RESTAURANT_ID,
	ZH_NAME, 
	CASE WHEN ENG_NAME = '' THEN NULL ELSE ENG_NAME END ENG_NAME,
	CAST(CASE WHEN STAR = '' THEN NULL ELSE STAR END AS DECIMAL(2,1)) STAR,
    CAST(CASE WHEN BOOKMARK = '' THEN NULL ELSE BOOKMARK END AS DECIMAL(7,0)) BOOKMARK,
    CASE WHEN DISTRICT = '' THEN NULL ELSE DISTRICT END DISTRICT,
    CASE WHEN PRICE = '' THEN NULL ELSE PRICE END PRICE,
    CASE WHEN CUISINE = '' THEN NULL ELSE CUISINE END CUISINE,
	CASE WHEN DISH = '' THEN NULL ELSE DISH END DISH,
    CASE WHEN ENG_ADDRESS = '' THEN NULL ELSE ENG_ADDRESS END ENG_ADDRESS,
    CASE WHEN ZH_ADDRESS = '' THEN NULL ELSE ZH_ADDRESS END ZH_ADDRESS,
    CAST(CASE WHEN EMOJI_SMILE = '' THEN NULL ELSE EMOJI_SMILE END AS DECIMAL(5,0)) EMOJI_SMILE,
	CAST(CASE WHEN EMOJI_OK = '' THEN NULL ELSE EMOJI_OK END AS DECIMAL(5,0)) EMOJI_OK,
    CAST(CASE WHEN EMOJI_CRY = '' THEN NULL ELSE EMOJI_CRY END AS DECIMAL(5,0)) EMOJI_CRY,
	CAST(CASE WHEN REVIEW_CNT = '' THEN NULL ELSE REVIEW_CNT END AS DECIMAL(5,0)) REVIEW_CNT,
	CAST(CASE WHEN PHOTO_CNT = '' THEN NULL ELSE PHOTO_CNT END AS DECIMAL(6,0)) PHOTO_CNT,
	CAST(CASE WHEN LATEST_REVIEW = '' THEN NULL ELSE LATEST_REVIEW END AS DATE) LATEST_REVIEW,
    CASE WHEN LAT = '' THEN NULL ELSE LAT END LAT,
    CASE WHEN LNG = '' THEN NULL ELSE LNG END LNG,
    CASE WHEN DISTRICTID = '' THEN NULL ELSE DISTRICTID END DISTRICTID,
    -- CASE WHEN CATEGORY = '' THEN NULL ELSE CATEGORY END CATEGORY,
    CASE WHEN CUISINE_CLEAN = '' THEN NULL ELSE CUISINE_CLEAN END CUISINE_CLEAN,
    CASE WHEN DISH_CLEAN = '' THEN NULL ELSE DISH_CLEAN END DISH_CLEAN,
	CASE WHEN AMENITY_CLEAN = '' THEN NULL ELSE AMENITY_CLEAN END AMENITY_CLEAN,
    CAST(NOW() AS DATE) AS UPDATE_DATE
FROM NEW_TBL
WHERE ZH_NAME != ''
AND SPECIAL = 'OPERATING'
AND ROW_NUNBER = 1;

-- CUISINE/ DISH/ AMENITY ARE ONE TO MANY RELATIONSHIP, CREATE MAPPING TABLE FOR THEM

-- MAX 4 CUISINE NUMBER
DROP TABLE IF EXISTS PUBLISH_RESTAURANTS_CUISINE;

CREATE TABLE PUBLISH_RESTAURANTS_CUISINE 
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(CUISINE_CLEAN, '[0-9]{4}') AS CUISINE_ID
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE CUISINE_CLEAN IS NOT NULL
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(CUISINE_CLEAN, '[0-9]{4}', 5, 1) AS CUISINE_ID
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(CUISINE_CLEAN) >= 9
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(CUISINE_CLEAN, '[0-9]{4}', 10, 1) AS CUISINE_ID
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(CUISINE_CLEAN) >= 14
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(CUISINE_CLEAN, '[0-9]{4}', 15, 1) AS CUISINE_ID
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(CUISINE_CLEAN) >= 19;



-- MAX 7 DISH NUMBER
DROP TABLE IF EXISTS PUBLISH_RESTAURANTS_DISH;

CREATE TABLE PUBLISH_RESTAURANTS_DISH 
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}') AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE DISH_CLEAN IS NOT NULL
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 5, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 9
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 10, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 14
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 15, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 19
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 20, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 24
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 25, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 29
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(DISH_CLEAN, '[0-9]{4}', 30, 1) AS DISH_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(DISH_CLEAN) >= 34;



-- MAX 5 AMENITY NUMBER
DROP TABLE IF EXISTS PUBLISH_RESTAURANTS_AMENITY;

CREATE TABLE PUBLISH_RESTAURANTS_AMENITY 
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(AMENITY_CLEAN, '[0-9]{4}') AS AMENITY_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE AMENITY_CLEAN IS NOT NULL
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(AMENITY_CLEAN, '[0-9]{4}', 5, 1) AS AMENITY_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(AMENITY_CLEAN) >= 9
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(AMENITY_CLEAN, '[0-9]{4}', 10, 1) AS AMENITY_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(AMENITY_CLEAN) >= 14
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(AMENITY_CLEAN, '[0-9]{4}', 15, 1) AS AMENITY_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(AMENITY_CLEAN) >= 19
UNION
SELECT  RESTAURANT_ID, REGEXP_SUBSTR(AMENITY_CLEAN, '[0-9]{4}', 20, 1) AS AMENITY_CLEAN
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE LENGTH(AMENITY_CLEAN) >= 24;

END //

DELIMITER ;
