/*
3. DATA ANALYSE - HONG KONG RESTAURANTS EXPLORATION

TO BE EXPLORED
RELATIONSHIP BETWEEN POPULARITY (BY BOOKMARK/ STAR) & DIFFERENT FEATURES (PRICE/ DISTIRCT/ CUISINE/ DISH ETC.)

*/
-- CUISINE
SELECT CATEGORY_ENG_NAME AS CUSIINE_NAME, CATEGORY_ZH_NAME AS CUSIINE_ZH_NAME, COUNT(DISTINCT A.RESTAURANT_ID) AS RESTAURANT_CNT, AVG(STAR) AVG_STAR, AVG(BOOKMARK) AVG_BOOKMARK
FROM OPENRICE.PUBLISH_RESTAURANTS A 
LEFT JOIN OPENRICE.PUBLISH_RESTAURANTS_CUISINE B
ON A.RESTAURANT_ID = B.RESTAURANT_ID
LEFT JOIN (SELECT * FROM OPENRICE.RAW_CATEGORIES WHERE CATEGORYTYPE = 'CUISINE') C 
ON B.CUISINE_ID = C.CATEGORYID
WHERE CATEGORY_ENG_NAME IS NOT NULL AND (A.STAR IS NOT NULL OR BOOKMARK IS NOT NULL)
GROUP BY CATEGORY_ENG_NAME, CATEGORY_ZH_NAME
HAVING COUNT(DISTINCT A.RESTAURANT_ID) >= 50
ORDER BY 4 DESC, 5 DESC

-- TOTAL
SELECT COUNT(DISTINCT RESTAURANT_ID) AS RESTAURANT_CNT, AVG(STAR) AVG_STAR, AVG(BOOKMARK) AVG_BOOKMARK
FROM OPENRICE.PUBLISH_RESTAURANTS
WHERE (STAR IS NOT NULL OR BOOKMARK IS NOT NULL)

-- DISH
SELECT CATEGORY_ENG_NAME AS DISH_NAME, CATEGORY_ZH_NAME AS DISH_ZH_NAME, COUNT(DISTINCT A.RESTAURANT_ID) AS RESTAURANT_CNT, AVG(STAR) AVG_STAR, AVG(BOOKMARK) AVG_BOOKMARK
FROM OPENRICE.PUBLISH_RESTAURANTS A 
LEFT JOIN OPENRICE.PUBLISH_RESTAURANTS_DISH B
ON A.RESTAURANT_ID = B.RESTAURANT_ID
LEFT JOIN (SELECT * FROM OPENRICE.RAW_CATEGORIES WHERE CATEGORYTYPE = 'DISH') C 
ON B.DISH_CLEAN = C.CATEGORYID
WHERE CATEGORY_ENG_NAME IS NOT NULL AND (A.STAR IS NOT NULL OR BOOKMARK IS NOT NULL)
GROUP BY CATEGORY_ENG_NAME, CATEGORY_ZH_NAME
HAVING COUNT(DISTINCT A.RESTAURANT_ID) >= 50
ORDER BY 4 DESC, 5 DESC


-- PRICE
SELECT PRICE, COUNT(DISTINCT A.RESTAURANT_ID) AS RESTAURANT_CNT, AVG(STAR) AVG_STAR, AVG(BOOKMARK) AVG_BOOKMARK
FROM OPENRICE.PUBLISH_RESTAURANTS A 
WHERE PRICE IS NOT NULL  AND (A.STAR IS NOT NULL OR BOOKMARK IS NOT NULL)
GROUP BY PRICE
HAVING COUNT(DISTINCT A.RESTAURANT_ID) >= 50
ORDER BY CASE WHEN PRICE = 'BELOW $50' THEN 1
				WHEN PRICE = '$51-100' THEN 2
				WHEN PRICE = '$101-200' THEN 3
                WHEN PRICE = '$201-400' THEN 4
                WHEN PRICE = '$401-800' THEN 5
                WHEN PRICE = 'ABOVE $801' THEN 6
                END